### ISSUE TITLE
打包乘压缩包的时机有问题

### ISSUE THREAD

**Issue by itmanyong** [KeJunMao/unplugin-compression#1]
1.在安装了插件`@vitejs/plugin-legacy`之后并启用
2.使用`npm run build`之后，压缩的执行时机在`legacy`之前。导致zip压缩包中的内容几乎没有

![image](https://user-images.githubusercontent.com/53500371/235634563-ce494e0b-fa58-4187-8a0f-d89dee523b8c.png)

**Comment by KeJunMao** [comment]
try v0.0.4
