### ISSUE TITLE
打包时可不可以不打包文件夹本身，而只打包文件夹中的内容

### ISSUE THREAD

**Issue by lvzhenbo** [KeJunMao/unplugin-compression#6]
一个比较特殊的需求，我正在用vite做chrome插件，想自动化打包，但是谷歌那边只需要文件而不是文件夹
这是现在的
![image](https://github.com/KeJunMao/unplugin-compression/assets/32427677/ef92389e-9bcc-4d90-9f19-ac26ccbac5b9)
需要的
![image](https://github.com/KeJunMao/unplugin-compression/assets/32427677/e8c804bc-e82a-45f4-b27b-e8e145416144)

**Comment by lvzhenbo** [comment]
参照[隔壁](https://github.com/pangyunchuan/vite-plugin-dist-zip#:~:text=%E5%8C%BA%E5%88%86%E5%8E%8B%E7%BC%A9%E5%8C%85-,includeDistDir,-%E5%B8%83%E5%B0%94)

**Comment by KeJunMao** [comment]
see v0.0.5, and use [compressingOptions](https://github.com/KeJunMao/unplugin-compression#compressingoptions)
